config:
  back-end-url: http://ec2-3-39-7-194.ap-northeast-2.compute.amazonaws.com:8080
  front-end-url: http://lunchselect.s3-website.ap-northeast-2.amazonaws.com
#  back-end-url: http://localhost:8080
#  front-end-url: http://localhost:3000
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://portfolio.cy4ymq3m97fp.ap-northeast-2.rds.amazonaws.com/lunchselect
    username: admin
    password: 1q2w3e4r
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: ${config.back-end-url}/login/oauth2/code/google
            client-id: 818987964691-r9qv978arlqlo7vvfffp8os9aar030h8.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          kakao:
            client-id: e45eb635f1167d472198e38d5c6dd06a
            redirect-uri: ${config.back-end-url}/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - account_email
          naver:
            client-id: ufgOMy9EVF1_jX5zkSYB
            client-secret: vgNf6Mvsnb
            redirect-uri: ${config.back-end-url}/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  mail:
    host: smtp.gmail.com
    port: 587
    username: jmclunchselect@gmail.com
    password: uxngkaoalppcywxt
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
              
mybatis:
  mapper-locations:
    - /mappers/*.xml 
    
jwt:
  secret: qJzUmGueQXDTxcXJyWUZa2oVwieBrVF41ozvRaHcW4uJ8Y4sJqHQC8WbvNoTC63k
  
server:
  max-http-header-size: 5MB
  
file:
  path: /ubuntu/upload
    
  

